<Project>
  <PropertyGroup>
    <Platforms>x64;ARM64</Platforms>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>Recommended</AnalysisMode>
    <_SkipUpgradeNetAnalyzersNuGetWarning>true</_SkipUpgradeNetAnalyzersNuGetWarning>
    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>moderate</NuGetAuditLevel>
    <WarningsAsErrors>$(WarningsAsErrors);NU1902;NU1903;NU1904</WarningsAsErrors>
    <WarningsNotAsErrors>$(WarningsNotAsErrors);APPX1707;CS8305;IL2081</WarningsNotAsErrors>
    <PlatformTarget>$(Platform)</PlatformTarget>
  </PropertyGroup>
</Project>
